name: UI Server of Jenkins AI

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/15 * * * *'  # Run every minute
  push:
    branches:
      - main

#env:
#  print_this: ${{ secrets.PRINT_THIS }}
#  print_this_var: ${{ vars.PRINT_THIS_VAR }}

jobs:
  build_webapp:
    name: Build
    #UI chat Server will be get built here.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      #Checkout the source code from the repository
      uses: actions/checkout@v4

    - name: Setup Python
      #Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      #Install Python dependencies and WebApp
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install .

  lint_webapp:
    name: Lint
    #flake8 has been used to test code lint sanity
    needs: build_webapp
    runs-on: ubuntu-latest

    steps:
    - name: Install requirements
      #Install Python dependencies for Flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Code Lint
      run: |
        python -m flake8

