name: Jynx - UI Server of Jenkins AI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_jynx:
    name: Build
    #UI chat Server will be get built here.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      #Checkout the source code from the repository
      uses: actions/checkout@v4

    - name: Setup Python
      #Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      #Install Python dependencies and WebApp
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install .

  lint_jynx:
    name: Lint
    #flake8 has been used to test code lint sanity
    needs: test_jynx
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      #Checkout the source code from the repository
      uses: actions/checkout@v4

    - name: Setup Python
      #Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      #Install Python dependencies for Flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt

    - name: Code Lint
      run: |
        python -m flake8

  test_jynx:
    name: Test
    needs: build_jynx
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      #Checkout the source code from the repository
      uses: actions/checkout@v4

    - name: Setup Python
      #Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      #Install Python dependencies for pytest, pytest-cov
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt

    - name: Run Tests and generate coverage.xml
      run: |
        pytest

  codequality_jynx:
    name: CodeQuality
    needs: test_jynx
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      #Checkout the source code from the repository
      uses: actions/checkout@v4

    #- name: Install tox and any other packages
    #  run: |
    #    python -m pip install --upgrade pip
    #    python -m pip install -r requirements_dev.txt

    #- name: Run tox
    #  run: tox -e py

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master #this is a github repo
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: src/jynx_ui
        args: >
          -Dsonar.organization=akatsukioshiro
          -Dsonar.projectKey=akatsukioshiro_test_repo
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.verbose=true
